#!/bin/bash

echo -e "\033[0;32mGenerating site and deploying to GitHub...\033[0m"

# Build the project.
hugo

# Add changes to git.
cd public
git add -A

# Commit changes.
msg="regenerating site on `date`."
if [ $# -eq 1 ]
  then msg="$1"
fi
git commit -m "$msg"

# Push source and build repos.
git push

cd ..
